config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # resources :comments
  # resources :posts do
  #   resources :comments
  # end

  # post 'posts/:post_id/comments/:comment_id', to: 'comments#create'
  root 'posts#index'

  scope shallow_prefix: "post" do
    resources :posts do
      resources :comments, shallow: true do
      end
    end
  end
  # post 'comments', to: 'comments#create'
  # POST '/comments/:id/comments/:id/foo/1' 
  resources :comments, only: [:create] do
    resources :comments, only: [:create]
  end
  # 관련한 기능이 없는지 알고 싶다.
end

# rails route 명령어를 통해 알수 있다.

#rails admin

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  # belongs_to :commentable, polymorphic: true
  # belongs_to :parent, class_name: 'Comment', optional: true
  # has_many :replies, class_name: 'Comment', foreign_key: :parent_id, dependent: :destroy
  belongs_to :post, optional: true
  belongs_to :comment, optional: true
  has_many :comments, dependent: :destroy
end

=begin

post = Post.find(2)

comments = post.comments
# Comment.where(post_id: 2)

comments.each do |comment|
  replies = comment.comments
  # Comment.where(comment_id: comment.id)
end

=end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments #, as: :commentable, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def show
        # @post = Post.find(params[:post_id])
        @comment = Comment.find(params[:id])
    end

    def create
        if params[:comment_id] == nil
            @post = Post.find(params[:post_id])
            @post.comments.create(
                params[:comment].permit(:name, :content),
            )
            redirect_to post_path(@post)
        else
            @comment = Comment.find(params[:comment_id])
            @comment.comments.create(
                name: params[:name], 
                content: params[:content],
                post: @comment.post
            )
            redirect_to post_path(@comment.post)
        end
    end

    def destroy
        @comment = Comment.find(params[:id])
        @post = @comment.post
        @comment.destroy
        redirect_to post_path(@post)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index
        @posts = Post.all.order("created_at DESC")
    end

    def new
        @post = Post.new
    end

    def create
        @post = Post.new(post_params)
        if @post.save
			redirect_to @post
		else
			render 'new'
		end
    end

    def show
        @post = Post.find(params[:id])
    end

    def update
        @post = Post.find(params[:id])
		if @post.update(post_params)
			redirect_to @post
		else
			render 'edit'
		end
	end

	def edit
		@post = Post.find(params[:id])
    end

    def destroy
		@post = Post.find(params[:id])
		@post.destroy

		redirect_to posts_path
	end


    private

    def post_params
        params.require(:post).permit(:title, :context)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="box">
  <article class="media">
    <div class="media-content">
      <div class="content">
        <p>
          <strong><%= comment.name %></strong>
          <%= comment.content %>
        </p>
      </div>
    </div>
     <%= link_to '대댓글달기', post_comment_path(comment),
                  method: :get, class: "button" %>
     <%= link_to 'Delete', post_comment_path(comment),
                  method: :delete, class: "button is-danger", data: { confirm: 'Are you sure?' } %>
  </article>
  <%= render comment.comments if comment.comments.any? %>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for([@post, @post.comments.build]) do |f| %>
  <!--
  collection.build(attributes = {}, …) Returns one or more new objects of the collection type that have been instantiated with attributes and linked to this object through a foreign key, but have not yet been saved. Note: This only works if an associated object already exists, not if it‘s nil!
  -->
  <div class="field">
    <div class="control">
      <%= f.input :name, input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' } %>
    </div>
  </div>
  
  <div class="field">
    <div class="control">
      <%= f.input :content, input_html: { class: 'textarea' }, wrapper: false, label_html: { class: 'label' }  %>
    </div>
  </div>
  <%= f.button :submit, 'Leave a reply', class: "button is-primary" %>
  <% end %>

app/views/comments/show.html.erb
<%= form_with(url: "/comments/#{@comment.id}/comments", method: "post") do %>
    <%= label_tag(:name, "name: ") %>
    <%= text_field_tag(:name) %>
    <%= label_tag(:content, "content: ") %>
    <%= text_field_tag(:content) %>
    <%= submit_tag("대댓글 달기") %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoBlog</title>
    <%= csrf_meta_tags %>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<section class="hero is-primary is-medium">
	  <!-- Hero head: will stick at the top -->
	  <div class="hero-head">
	    <nav class="navbar">
	      <div class="container">
	        <div class="navbar-brand">
	          <%= link_to 'Demo Blog', root_path, class: "navbar-item" %>
	          <span class="navbar-burger burger" data-target="navbarMenuHeroA">
	            <span></span>
	            <span></span>
	            <span></span>
	          </span>
			</div>
			<%= link_to "Create New Post", new_post_path, class:"navbar-item" %>
	      </div>
	    </nav>
	  </div>

	  <!-- Hero content: will be in the middle -->
	  <div class="hero-body">
	    <div class="container has-text-centered">
	      <h1 class="title">
	        <%= yield :page_title %>
	      </h1>
	    </div>
	  </div>
	</section>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="section">
<%= simple_form_for @post do |f| %>
  <div class="field">
    <div class="control">
      <%= f.input :title, input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' } %>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= f.input :context, input_html: { class: 'textarea' }, wrapper: false, label_html: { class: 'label' }  %>
    </div>
  </div>
  <%= f.button :submit, 'Create new post', class: "button is-primary" %>
<% end %>
</div>

app/views/posts/edit.html.erb
<% content_for :page_title, "Edit Post" %>
<%= render 'form' %>

app/views/posts/index.html.erb
<% content_for :page_title,  "Index" %>

<div class="section">
	<div class="container">
		<% @posts.each do |post| %>
			<div class="card">
		  <div class="card-content">
		    <div class="media">
		      <div class="media-content">
		        <p class="title is-4"><%= link_to post.title, post  %></p>
		      </div>
		    </div>
		    <div class="content">
		     	<%= post.context %>
		    </div>
		    
		  </div>
		</div>
		<% end %>
	</div>
</div>

app/views/posts/new.html.erb
<% content_for :page_title, "Create a new post" %>
<%= render 'form' %>

app/views/posts/show.html.erb
<% content_for :page_title, @post.title %>

<section class="section">
	<div class="container">
		<nav class="level">
		  <!-- Left side -->
		  <div class="level-left">
		    <p class="level-item">
		        <strong>Actions</strong>
		    </p>
		  </div>
		  <!-- Right side -->
		  <div class="level-right">
		  	<p class="level-item">
		    	<%= link_to "Edit", edit_post_path(@post), class:"button" %>
		  	</p>
		  	<p class="level-item">
                <%= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure?" }, class:"button is-danger" %>
			</p>
		  </div>
		</nav>
		<hr/>

        <div class="content">
			<%= @post.context %>
		</div>
	</div>
</section>

<section class="section comments">
	<div class="container">
		<h2 class="subtitle is-5"><strong><%= @post.comments.count %></strong> Comments</h2>
		# <%= render @post.comments.where(comment: nil) %>
		<%= render @post.comments.where(comment: nil) %>
		<div class="comment-form">
			<hr />
			<h3 class="subtitle is-3">Leave a reply</h3>
	 		<%= render 'comments/form' %>
		</div>
	</div>
</section>